export const VIDEOWIDTH_PORTRAIT = 100;
export const VIDEOHEIGHT_PORTRAIT = (VIDEOWIDTH_PORTRAIT / 16) * 9;

export const VIDEOWIDTH_LANDSCAPE = 85;
export const VIDEOHEIGHT_LANDSCAPE = (VIDEOWIDTH_LANDSCAPE / 16) * 9;
